const fs=require('fs'),ts=require(process.cwd()+'/node_modules/typescript'),assert=require('node:assert/strict');
const mod={exports:{}};new Function('exports','require','module',ts.transpileModule(fs.readFileSync('components/ui/table-query.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(mod.exports,require,mod);
const {queryRows,optionsFor,filterError,day,EMPTY,managementColumns,reportColumns}=mod.exports;
const cols=[{key:'title',label:'ชื่อ',kind:'text'},{key:'salary',label:'เงินเดือน',kind:'number'},{key:'year',label:'ปี',kind:'select'},{key:'when',label:'วันที่',kind:'date'}];
const rows=[{id:1,title:'Career 10',salary:'50000',year:2570,when:'2026-09-26T18:00:00Z'},{id:2,title:'Career 2',salary:9000,year:2564,when:'2026-09-26T16:59:59Z'},{id:3,title:'อื่น',salary:null,year:null,when:null},{id:4,title:'Career 1',salary:15000,year:2564,when:'2026-09-27T16:59:59Z'}];
const ids=(filters={},sort=null)=>queryRows(rows,cols,filters,sort).map(r=>r.id);
assert.deepEqual(ids({}, {key:'salary',direction:'asc'}),[2,4,1,3]);
assert.deepEqual(ids({}, {key:'salary',direction:'desc'}),[1,4,2,3]);
assert.deepEqual(ids({}, {key:'title',direction:'asc'}).filter(i=>i!==3),[4,2,1]);
assert.deepEqual(ids({salary:{min:'9000',max:'15000'}}),[2,4]);
assert.deepEqual(ids({title:{text:' CAREER '},year:{value:'2564'},salary:{min:'10000'}}),[4]);
assert.deepEqual(ids({salary:{max:'10000'}}),[2]);
assert.deepEqual(ids({year:{value:EMPTY}}),[3]);
assert.deepEqual(optionsFor(cols[2],rows).map(o=>o.value),['2564','2570',EMPTY]);
assert.equal(day(rows[0].when),'2026-09-27');
assert.deepEqual(ids({when:{min:'2026-09-27',max:'2026-09-27'}}),[1,4]);
assert.deepEqual(ids({title:{text:'ไม่มีรายการ'}}),[]);
assert.ok(filterError(cols,{salary:{min:'20',max:'10'}}));
assert.ok(filterError(cols,{salary:{min:'-1'}}));
assert.ok(filterError(cols,{when:{min:'2026-09-28',max:'2026-09-27'}}));
assert.equal(filterError(cols,{salary:{min:'0',max:'0'}}),'');
assert.deepEqual(rows.map(r=>r.id),[1,2,3,4]);
assert.deepEqual(queryRows([],cols,{},null),[]);
assert.deepEqual(ids(),[1,2,3,4]);
const report=reportColumns('unanswered');
assert.deepEqual(queryRows([{resolved:false},{resolved:true}],report,{resolved:{value:'false'}},null),[{resolved:false}]);
const schema=managementColumns({columns:['curriculum_year','major_id','tuition_fee'],fields:[{key:'curriculum_year',type:'number'},{key:'major_id',type:'major'},{key:'tuition_fee',type:'number'}]}, {majors:[{id:1,major_name_th:'วิทยาการคอมพิวเตอร์'}]});
assert.deepEqual(schema.map(c=>c.kind),['select','select','number']);
assert.equal(optionsFor(schema[1],[{major_id:1}])[0].label,'วิทยาการคอมพิวเตอร์');
assert.deepEqual(optionsFor({key:'role',label:'บทบาท',kind:'select'},[{role:'staff'}]).map(o=>o.value),['staff']);
console.log('22 table query checks passed');
